### ISSUE TITLE
Loading the environment with episode length of 150 instead of 500

### ISSUE THREAD

**Issue by gunnxx** [TToTMooN/paco-mtrl#1]
Is it true that the code loads the environment with episode length of 150 instead of 500?
```
alf.config(
    'create_environment',
    env_name=env_name,
    num_parallel_environments=num_of_parallel_envs,
    env_load_fn=partial(
        suite_metaworld.load_mt_benchmark,
        sample_strategy=sample_strategy,
    ),
    nonparallel=False)

alf.config(
    'create_eval_environment',
    env_name=env_name,
    num_parallel_environments=1,
    env_load_fn=partial(
        suite_metaworld.load_mt_benchmark,
        sample_strategy='robin',
    ),
    nonparallel=True)
```

This is the environment loading function
```
@alf.configurable
def load_mt_benchmark(environment_name,
                      env_id=None,
                      discount=1.0,
                      max_episode_steps=150,
                      seed=0,
                      sample_strategy='uniform',
                      sample_goal=False,
                      gym_env_wrappers=(),
                      alf_env_wrappers=()):
    assert environment_name in ['mt10', 'mt50']
    if environment_name == 'mt10':
        mt_benchmark = metaworld.MT10(seed=seed)
    else:
        mt_benchmark = metaworld.MT50(seed=seed)
    envs = []
    goal_dict = {} if sample_goal else None
    random.seed(seed)
    for env_name, env_cls in mt_benchmark.train_classes.items():
        print(env_name)
        env = env_cls()
        env_tasks = [
            task for task in mt_benchmark.train_tasks
            if task.env_name == env_name
        ]
        task = random.choice(env_tasks)
        env.set_task(task)
        if goal_dict is not None:
            goal_dict[env_name] = env_tasks
        if not max_episode_steps:  # None or 0
            max_episode_steps = env.max_path_length
        max_episode_steps = min(env.max_path_length, max_episode_steps)
        env = suite_gym.wrap_env(
            env,
            env_id=env_id,
            discount=discount,
            gym_env_wrappers=gym_env_wrappers,
            alf_env_wrappers=alf_env_wrappers)
        envs.append(env)
    environment_name_list = [t[0] for t in mt_benchmark.train_classes.items()]
    mtenv = MultitaskMetaworldWrapper(
        envs,
        task_names=environment_name_list,
        goal_dict=goal_dict,
        sample_strategy=sample_strategy,
        env_id=env_id)
    mtenv = alf_wrappers.TimeLimit(mtenv, duration=max_episode_steps)
    return mtenv
```

**Comment by TToTMooN** [comment]
We use 150 for MetaWorld tasks, as Table 8 in A2.2 mentions.

MetaWorld v2 changes all tasks' reward functions and extends the default max episode length to avoid potential failure due to insufficient length. The max episode length is not part of the task MDP and can be adjusted by users. (There's no 'done' signal return, and the success evaluation is based on the existence of success in the trajectory. )

However, during training, we observed 
1. 150, the length used in v1 implementations, is enough to finish the tasks. Most tasks have plenty of remaining time after success, even in the 150 cases. Generally, finishing tasks faster is better, although this does not affect the success rate. See examples of successful tasks in episode of 150 steps.
![paco_mt10](https://github.com/TToTMooN/paco-mtrl/assets/8488908/036626eb-7a90-4092-a25d-c68089c1b541)

2. setting max_path_length too long would make the training less efficient for single and multi-task training. Using the baseline and our method, it takes more steps to reach similar performance. If all the methods are using the same max_path_length, t
hen the comparison is fair.

Choosing a different max_path_length or using the default one should not affect the proposed method and the baselines much.

**Comment by gunnxx** [comment]
Hi, thanks for the quick response!

Couple of follow ups:
1. In figure 7, it says `Compositional vector for each task in MT10-fixed task. This is a policy reaching 100% success rate for all fixed-goal tasks.` Can you explain a little bit more about what does it mean? If it reaches 100% for all fixed-goal tasks, then why the result in Table 4 is not 100% (ie. 93.3 ± 5.8 %)?
2. When I tried to run the code, somehow the environment is not reseting automatically. It gave me `ValueError: Maximum path length allowed by the benchmark has been exceeded`. The trace comes from `metaworld.envs.mujoco.mujoco_env.MujocoEnv.do_simulation()`. I guess because the `curr_path_length` is not being reset when `reset` is called. Or did I miss something? This is the code from `metaworld.envs.mujoco.sawyer_xyz.sawyer_xyz_env.SawyerXYZEnv.reset()`
```
    def reset(self):
        if not self.isV2:
            self.curr_path_length = 0
            return super().reset()
        else:
            obs = np.float64(super().reset())
            self._prev_obs = obs[:18].copy()
            obs[18:36] = self._prev_obs
            return obs
```

**Comment by gunnxx** [comment]
For 2, seems like it is caused by a PR two weeks ago on metaworld repo ([Fixing issues #401](https://github.com/Farama-Foundation/Metaworld/pull/401)). What is left is the first question, hope you can explain a little bit more. Thanks!

**Comment by Haichao-Zhang** [comment]
> 1. In figure 7, it says `Compositional vector for each task in MT10-fixed task. This is a policy reaching 100% success rate for all fixed-goal tasks.` Can you explain a little bit more about what does it mean? If it reaches 100% for all fixed-goal tasks, then why the result in Table 4 is not 100% (ie. 93.3 ± 5.8 %)?

Thanks for your interest in our work! And it's great that you've already resolved the second question.

For your first question:
1. In Figure 7,  we show the compositional vectors learned during  *one training session*. For this particular training session, the final evaluation performance of the trained policy is ~ 100% (fixed goals).  There is no particular reason for using this particular training session. Others could also be used.
2. The final performance of the policies from difference training sessions (with different random seeds) can be different, due to randomness in NN initializations etc.  The result you mentioned in Table 4 reflects exactly this aspect: the evaluation performance averaged across multiple training sessions is 93.3% and the std is  5.8%.

Please let us know if you have any further questions.

**Comment by gunnxx** [comment]
Got it, that's very clear. Thanks!
